server:
  port: 8080

spring:
  application:
    name: RecruitmentSystem

  datasource:
    url: jdbc:mysql://localhost:3306/job_recruitment_system?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: root
    password: phanloc2702

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

jwt:
  signerKey: "tZwa1Se0sysrRZ9Bv0NOs4CWEUK2JTA8rDk9etuliNEl920NUbOzeUcsPHM88btR"